/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiAnalyzeFoodRouteImport } from './routes/api/analyze-food'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedProgressRouteImport } from './routes/_authed/progress'
import { Route as AuthedAnalyticsRouteImport } from './routes/_authed/analytics'
import { Route as AuthedAddRouteImport } from './routes/_authed/add'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeFoodRoute = ApiAnalyzeFoodRouteImport.update({
  id: '/api/analyze-food',
  path: '/api/analyze-food',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProgressRoute = AuthedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsRoute = AuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAddRoute = AuthedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add': typeof AuthedAddRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/progress': typeof AuthedProgressRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/analyze-food': typeof ApiAnalyzeFoodRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add': typeof AuthedAddRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/progress': typeof AuthedProgressRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/analyze-food': typeof ApiAnalyzeFoodRoute
  '/api/coach': typeof ApiCoachRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/add': typeof AuthedAddRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/progress': typeof AuthedProgressRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/api/analyze-food': typeof ApiAnalyzeFoodRoute
  '/api/coach': typeof ApiCoachRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/add'
    | '/analytics'
    | '/progress'
    | '/settings'
    | '/api/analyze-food'
    | '/api/coach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/add'
    | '/analytics'
    | '/progress'
    | '/settings'
    | '/api/analyze-food'
    | '/api/coach'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/add'
    | '/_authed/analytics'
    | '/_authed/progress'
    | '/_authed/settings'
    | '/api/analyze-food'
    | '/api/coach'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAnalyzeFoodRoute: typeof ApiAnalyzeFoodRoute
  ApiCoachRoute: typeof ApiCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-food': {
      id: '/api/analyze-food'
      path: '/api/analyze-food'
      fullPath: '/api/analyze-food'
      preLoaderRoute: typeof ApiAnalyzeFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/progress': {
      id: '/_authed/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthedProgressRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/add': {
      id: '/_authed/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthedAddRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAddRoute: typeof AuthedAddRoute
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedProgressRoute: typeof AuthedProgressRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAddRoute: AuthedAddRoute,
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedProgressRoute: AuthedProgressRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAnalyzeFoodRoute: ApiAnalyzeFoodRoute,
  ApiCoachRoute: ApiCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
